[package]
name = "antimodern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.7.3"
cgmath = "0.18.0"
tokio = { version = "1.15.0", features = ["full"] }
wgpu = "0.12.0"
winit = "0.26.1"
